from utility import Config


def get_test_config():
    return Config(
        architecture='decoder-transformer',
        bias=True,
        d_model=16,
        d_feedforward=16,
        dropout=0.0,
        num_heads=4,
        num_layers=1,
        use_attn_mask=False,
        positional_encoding='learned',
        batch_size=24,
        context_len=16,
        dataset='southpark',
        num_samples=100,
        split_ratios='90-5-5',
        vocab_size=512,
        device='cpu',
        beta1=0.9,
        beta2=0.999,
        gradient_accumulation_steps=1,
        gradient_clip_value=1.0,
        lr=0.0001,
        lr_decay_iters=10000,
        min_lr=1e-05,
        optimizer_type='Adam',
        scheduler_type='None',
        use_gradient_clipping=True,
        warmup_steps=2000,
        weight_decay=0.1,
        epochs=1,
        pretrained_model='',
        save_model_every_epoch=True,
        tokenizer_type='bpe-metaspace-punctuation-512',
        log_text_samples=True,
        max_len_generate=300,
        temperature=1.0,
        beam_search=False,
        log_wandb=False,
        evaluation_interval=100,
    )
